
GET
   FILE='C:\Users\etnik\OneDrive\Desktop\ndikimi.sav'.
 DATASET NAME DataSet0 WINDOW=FRONT.
 SAVE OUTFILE='C:\Users\etnik\OneDrive\Desktop\ndikimi.sav' /COMPRESSED.
 SAVE OUTFILE='C:\Users\etnik\OneDrive\Desktop\ndikimi.sav' /COMPRESSED.
 FREQUENCIES VARIABLES=Gjinia Mosha Statusi_profesional Shpeshtehsia_blerjes Kanali_i_perferuar
   /ORDER=ANALYSIS.
DESCRIPTIVES VARIABLES=BL1 BL2 BL3 BL4
   /STATISTICS=MEAN STDDEV SEMEAN.
DESCRIPTIVES VARIABLES=CP1 CP2 CP3 CP4
   /STATISTICS=MEAN STDDEV.
DESCRIPTIVES VARIABLES=DT1 DT2 DT3
   /STATISTICS=MEAN STDDEV SEMEAN.
RELIABILITY
   /VARIABLES=BS1 BS2 BS3 BS4 BL1 BL2 BL3 BL4 CP1 CP2 CP3 CP4 DT1 DT2 DT3
   /SCALE('ALL VARIABLES') ALL
   /MODEL=ALPHA.
REGRESSION
   /MISSING LISTWISE
   /STATISTICS COEFF OUTS R ANOVA
   /CRITERIA=PIN(.05) POUT(.10)
   /NOORIGIN
   /DEPENDENT BS_mesatarja
   /METHOD=ENTER DT_mesatarja.
UNIANOVA BS_mesatarja BY Gjinia Mosha
   /METHOD=SSTYPE(3)
   /INTERCEPT=INCLUDE
   /EMMEANS=TABLES(Gjinia)
   /EMMEANS=TABLES(Mosha)
   /PRINT=HOMOGENEITY DESCRIPTIVE
   /CRITERIA=ALPHA(.05)
   /DESIGN=Gjinia Mosha Gjinia*Mosha.
REGRESSION
   /MISSING LISTWISE
   /STATISTICS COEFF OUTS R ANOVA
   /CRITERIA=PIN(.05) POUT(.10)
   /NOORIGIN
   /DEPENDENT BL_mesatarja
   /METHOD=ENTER CP_mesatarja.















